"""资产包管理：pack.json 清单 + sha256 校验 + Tier-0/1 两级检索 + zip 分发。

A pack is a self-contained unit of reusable assets::

    packs/<id>/
    ├── pack.json          # manifest (schema below)
    ├── module_gen.py      # optional generator for the pack's modules
    ├── modules/<category>/<name>.schem (+ .module.json)
    ├── styles/*.json      # optional material/style packs
    └── catalog.md        # Tier-0 compact catalog (generated by `scan`)
  previews/*.png     # optional preview images (indexed into pack.json)

Manifest schema::

    {
      "id": "modern-arch", "name": "...", "version": "1.0.0",
      "description": "...", "author": "...", "license": "MIT",
      "mc_versions": ["1.21.4"], "engine_requires": ">=0.2.0",
      "dependencies": {},
      "provides": {"modules": [...], "styles": [...], "generator": "..."},
      "previews": {"office_room": "previews/office_room.png"},
      "files": {"<rel>": "sha256:<hex>"},   # every file except pack.json
      "tags": [...]
    }

Commands:
  list        table of packs
  scan        rebuild packs/index.json, refresh every pack.json + catalog.md
  validate    manifest schema + files(sha256) + dependencies + previews
  catalog     generate Tier-0 compact catalog (per pack or all packs)
  search      Tier-1 structured search inside a pack (or all packs)
  export      build dist/<id>-<version>.zip for distribution
  import      install a pack zip (checksum-verified, dependency-checked)
  import-modules  batch-import structure files as modules (auto size/spec/dedupe)
  previews    render preview images for a pack's modules
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import zipfile
from functools import lru_cache
from pathlib import Path

from mccore import structure_io as S
from mccore.module_lib import INDEX, filter_entries, scan as module_scan
from mccore.paths import (ensure_packs_dir, pack_dirs, packs_dir,
                          repo_root, write_text_lf)

SEMVER = re.compile(r"^\d+\.\d+\.\d+$")
ID_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9._-]*$")
EXCLUDE_PARTS = {"__pycache__", ".git", ".cache", "out", "dist",
                 ".pytest_cache", "node_modules", "venv", ".venv"}
EXCLUDE_SUFFIX = {".pyc", ".pyo"}
SKIP_NAMES = {".DS_Store", "Thumbs.db"}


@lru_cache(maxsize=1)
def _git_author() -> str:
    """仓库的 ``git config user.name``（只查一次，失败就空串）。

    **必须只看不炸**：这是个「填默认值」的辅助函数，而测试里常把
    ``subprocess.run`` 整体打桩（比如预览队列冒烟），任何异常外泄都会把
    无关的调用方一起带崩 —— 所以这里用宽 except + 缓存。
    """
    try:
        r = subprocess.run(["git", "config", "--get", "user.name"],
                           cwd=str(repo_root()), capture_output=True,
                           text=True, timeout=5)
    except Exception:  # noqa: BLE001 —— 没 git / 被打桩 / 超时都算“不知道”
        return ""
    name = (r.stdout or "").strip()
    return name if r.returncode == 0 else ""


def default_author() -> str:
    """新 pack.json 的默认 author：**不写死任何人的名字**。

    顺序：``STRUCTWORKSHOP_AUTHOR`` 环境变量 -> 仓库的 ``git config user.name``
    -> ``"unknown"``。这样在别人机器上 ``pack create/scan`` 出来的是他自己的署名。
    环境变量每次现读（测试/CI 会中途改），git 查询带缓存。
    """
    env = os.environ.get("STRUCTWORKSHOP_AUTHOR")
    if env and env.strip():
        return env.strip()
    return _git_author() or "unknown"


def load_manifest(p: Path) -> dict:
    return json.loads((p / "pack.json").read_text(encoding="utf-8"))


def semver(v) -> str:
    if isinstance(v, (int, float)):
        v = str(int(v))
    parts = str(v).strip().split(".")
    parts = [p for p in parts if p.isdigit()]
    while len(parts) < 3:
        parts.append("0")
    return ".".join(parts[:3])


def fill_manifest_defaults(m: dict, pd: Path) -> dict:
    m.setdefault("name", m.get("id", pd.name))
    m["version"] = semver(m.get("version", "1.0.0"))
    m.setdefault("description", "")
    m.setdefault("author", default_author())
    m.setdefault("license", "MIT")
    m.setdefault("mc_versions", ["1.21.4"])
    m.setdefault("engine_requires", ">=0.2.0")
    m.setdefault("dependencies", {})
    m.setdefault("tags", [])
    m.setdefault("provides", {})
    m["provides"].setdefault("modules", [])
    m["provides"].setdefault("styles", [])
    m["provides"].setdefault("generator", None)
    m.setdefault("previews", {})
    m.setdefault("files", {})
    return m


def iter_pack_files(pd: Path):
    """Yield (posix_rel_path, Path) for every distributable file in a pack."""
    for f in sorted(pd.rglob("*")):
        if not f.is_file():
            continue
        rel = f.relative_to(pd).as_posix()
        if set(Path(rel).parts) & EXCLUDE_PARTS:
            continue
        if f.suffix.lower() in EXCLUDE_SUFFIX:
            continue
        if f.name in SKIP_NAMES:
            continue
        yield rel, f


def file_sha256(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def load_index() -> dict:
    if not INDEX.exists():
        module_scan()
    return json.loads(INDEX.read_text(encoding="utf-8"))


def refresh_manifest(pd: Path, idx: dict | None = None, write: bool = True) -> dict:
    """Normalize pack.json: defaults, provides, previews, files(sha256)."""
    m = load_manifest(pd)
    fill_manifest_defaults(m, pd)
    idx = idx or load_index()
    mods = sorted(idx.get("packs", {}).get(m["id"], {}).get("modules", []))
    m["provides"]["modules"] = mods
    styles = []
    sd = pd / "styles"
    if sd.is_dir():
        styles = sorted(f.relative_to(pd).as_posix().replace("\\", "/")
                        for f in sd.glob("*.json"))
    m["provides"]["styles"] = styles
    gen = pd / "module_gen.py"
    m["provides"]["generator"] = "module_gen.py" if gen.is_file() else None
    previews = {}
    for mid in mods:
        e = idx.get("modules", {}).get(mid, {})
        prev = e.get("preview")
        if prev:
            rel = Path(prev).as_posix()
            prefix = f"{m['id']}/"
            if rel.startswith(prefix):
                rel = rel[len(prefix):]
            previews[mid] = rel
    m["previews"] = previews
    files = {}
    for rel, f in iter_pack_files(pd):
        if rel == "pack.json":
            continue
        files[rel] = file_sha256(f)
    m["files"] = files
    if write:
        write_text_lf(pd / "pack.json", 
            json.dumps(m, ensure_ascii=False, indent=2) + "\n")
    return m


def write_catalog(pd: Path, idx: dict, pack_relative: bool = True,
                  write: bool = True) -> list[str]:
    """Tier-0: Markdown table catalog inside the pack dir."""
    pack = pd.name
    rows = sorted((e for e in idx["modules"].values()
                   if e.get("pack") == pack),
                  key=lambda r: (r["category"], r["id"]))
    lines = [
        f"# {pack} 资产包 Tier-0 目录",
        "",
    ]
    for r in rows:
        top = sorted(r["palette"].items(), key=lambda kv: -kv[1])[:3]
        mats = ",".join(k for k, _v in top if k != "air") or "-"
        tags = " ".join(r["tags"]) or "-"
        desc = r["description"] or "-"
        tax = r.get("taxonomy") or {}
        cls = "/".join(str(tax[k]) for k in ("movement", "facade", "props")
                       if tax.get(k)) or "-"
        raw_prev = r.get("preview") or "-"
        if raw_prev != "-":
            if pack_relative and raw_prev.startswith(pack + "/"):
                prev = raw_prev[len(pack) + 1:]
            else:
                prev = raw_prev
        else:
            prev = "-"
        img = f"![{r['id']}]({prev})" if prev != "-" else "-"
        lines.append(
            f"- **{r['id']}** · {r['category']} · "
            f"{'x'.join(map(str, r['size']))} · {r['blocks']}块 · "
            f"材料:{mats} · 接口:{len(r['ports'])} · "
            f"标签:{tags} · 分类:{cls} · 描述:{desc} · 预览:{img}")
    write_text_lf(pd / "catalog.md", "\n".join(lines) + "\n") if write else None
    return lines


def master_catalog_text(pds: list[Path], idx: dict) -> str:
    """``packs/catalog.md`` 的**字节级内容**（写盘与校验共用）。"""
    chunks = [
        f"# 结构工坊 资产包总目录 (Tier-0)",
        "",
        f"- 资产包数: {len(pds)}",
        f"- 模块数: {len(idx['modules'])}",
    ]
    for pd in pds:
        chunks.append("")
        chunks.append(f"## {pd.name}")
        chunks.append("")
        chunks.extend(write_catalog(pd, idx, pack_relative=False,
                                    write=False)[2:])
    return "\n".join(chunks) + "\n"


def write_master_catalog(pds: list[Path], idx: dict) -> Path:
    out = ensure_packs_dir() / "catalog.md"
    write_text_lf(out, master_catalog_text(pds, idx))
    return out


def cmd_list(_a) -> None:
    pds = pack_dirs()
    idx = load_index()
    print(f"{'id':18} {'版本':8} {'模块':>4} {'风格':>3} {'预览':>4} 名称")
    for pd in pds:
        m = load_manifest(pd)
        fill_manifest_defaults(m, pd)
        mods = idx.get("packs", {}).get(m["id"], {}).get("modules", [])
        styles = sum(1 for _ in (pd / "styles").glob("*.json")) \
            if (pd / "styles").is_dir() else 0
        prev = sum(1 for _ in (pd / "previews").glob("*.png")) \
            if (pd / "previews").is_dir() else 0
        print(f"{m['id']:18} {m['version']:8} {len(mods):>4} {styles:>3} "
              f"{prev:>4}  {m.get('name', '')[:36]}")


def rescan_manifests(idx: dict | None = None, *, quiet: bool = False) -> list[Path]:
    """重建各包的 catalog.md + pack.json（sha256 / previews）并写总目录。

    除了 CLI，Web 端批量渲染预览图后也要调它，否则 pack.json 的 files/previews
    会和新生成的预览图对不上（``python -m mccore.pack validate`` 会报哈希/缺失）。
    """
    idx = idx or module_scan()
    pds = list(pack_dirs())
    for pd in pds:
        n = len(write_catalog(pd, idx))
        refresh_manifest(pd, idx=idx, write=True)
        if not quiet:
            print(f"pack {pd.name}: {n - 2} 个模块 -> catalog.md + pack.json")
    master = write_master_catalog(pds, idx)
    if not quiet:
        print(f"master catalog -> {master}")
    return pds


def cmd_scan(_a) -> None:
    rescan_manifests()


def cmd_validate(_a) -> None:
    errs: list[str] = []
    warns: list[str] = []
    pack_ids = {pd.name for pd in pack_dirs()}
    seen: dict[str, str] = {}
    idx = load_index()
    for pd in pack_dirs():
        m = load_manifest(pd)
        fill_manifest_defaults(m, pd)
        if m.get("id") != pd.name:
            errs.append(f"{pd.name}: pack.json id={m.get('id')} != 目录名")
        if not SEMVER.match(m["version"]):
            errs.append(f"{pd.name}: version 不是 semver: {m['version']}")
        for key in ("author", "license", "engine_requires"):
            if not isinstance(m.get(key), str) or not m.get(key):
                errs.append(f"{pd.name}: 缺 {key}")
        if not isinstance(m.get("mc_versions"), list) or not m["mc_versions"]:
            errs.append(f"{pd.name}: mc_versions 必须是非空列表")
        deps = m.get("dependencies", {})
        if not isinstance(deps, dict):
            errs.append(f"{pd.name}: dependencies 必须是对象")
        else:
            for dep in deps:
                if dep not in pack_ids:
                    errs.append(f"{pd.name}: 依赖的资产包不存在: {dep}")
        mdir = pd / "modules"
        if not mdir.is_dir():
            errs.append(f"{pd.name}: 缺 modules/ 目录")
        else:
            mods = sorted({p for suf in S.SUPPORTED_SUFFIXES
                           for p in mdir.rglob("*" + suf)})
            for lt in mods:
                if not lt.with_suffix(".module.json").exists():
                    errs.append(f"{pd.name}: {lt.name} 缺 sidecar spec")
                if lt.stem in seen:
                    errs.append(f"{pd.name}: 模块 id 冲突 {lt.stem} "
                                f"(也存在于 {seen[lt.stem]})")
                seen[lt.stem] = pd.name
        for style in m.get("provides", {}).get("styles", []):
            if not (pd / style).is_file():
                errs.append(f"{pd.name}: 声明的风格文件不存在: {style}")
        gen = m.get("provides", {}).get("generator")
        if gen and not (pd / gen).is_file():
            errs.append(f"{pd.name}: 声明的 generator 不存在: {gen}")
        for mid, rel in m.get("previews", {}).items():
            if not (pd / rel).is_file():
                errs.append(f"{pd.name}: previews[{mid}] 不存在: {rel}")
        for mid in m.get("provides", {}).get("modules", []):
            e = idx.get("modules", {}).get(mid, {})
            if e and not e.get("preview"):
                warns.append(f"{pd.name}/{mid}: 没有预览图 "
                             f"(可运行 python -m mccore.pack previews {pd.name})")
        files = m.get("files", {})
        if not files:
            warns.append(f"{pd.name}: files 为空, 先运行 pack scan")
        for rel, sha in files.items():
            f = pd / rel
            if not f.is_file():
                errs.append(f"{pd.name}: files 记录的文件不存在: {rel}")
            elif file_sha256(f) != sha:
                errs.append(f"{pd.name}: 校验和失败: {rel}")
    if errs:
        print("ERRORS:")
        for e in errs:
            print("  !", e)
        raise SystemExit(1)
    print(f"packs OK ({len(seen)} 模块, {len(pack_ids)} 包)")
    for w in warns:
        print("  warn:", w)


def cmd_catalog(a) -> None:
    idx = load_index()
    if a.pack:
        pd = packs_dir() / a.pack
        if not (pd / "pack.json").is_file():
            raise SystemExit(f"没有资产包 {a.pack}")
        lines = write_catalog(pd, idx)
        print(f"{pd / 'catalog.md'}: {len(lines) - 2} 个模块")
        return
    pds = pack_dirs()
    master = write_master_catalog(pds, idx)
    print(f"{master}: {len(pds)} 个包, {len(idx['modules'])} 个模块")


def cmd_search(a) -> None:
    idx = load_index()
    rows = filter_entries(
        list(idx["modules"].values()),
        pack=a.pack, category=a.category, tag=a.tag, query=a.query,
        material=a.material, min_blocks=a.min_blocks, max_blocks=a.max_blocks,
        has_port=False if a.no_port else a.has_port)
    rows = sorted(rows, key=lambda r: (r.get("pack", ""), r["category"],
                                       r["id"]))
    if a.json:
        print(json.dumps(rows, ensure_ascii=False, indent=1))
        return
    print(f"{'id':22} {'包':15} {'类别':10} {'尺寸':10} {'方块':>6} "
          f"{'口':>2} 标签 / 预览")
    for r in rows:
        prev = r.get("preview") or "-"
        print(f"{r['id']:22} {r.get('pack', ''):15} {r['category']:10} "
              f"{'x'.join(map(str, r['size'])):10} {r['blocks']:>6} "
              f"{len(r['ports']):>2}  {' '.join(r['tags'])} / {prev}")
    print(f"\n{len(rows)} 条")


def cmd_export(a) -> None:
    pd = packs_dir() / a.pack
    if not (pd / "pack.json").is_file():
        raise SystemExit(f"没有资产包 {a.pack}")
    m = refresh_manifest(pd, write=True)
    out_dir = Path(a.out).expanduser() if a.out else repo_root() / "dist"
    out_dir.mkdir(parents=True, exist_ok=True)
    zip_path = out_dir / f"{m['id']}-{m['version']}.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        count = 0
        for rel, f in iter_pack_files(pd):
            z.write(f, arcname=rel)
            count += 1
    size = zip_path.stat().st_size
    print(f"导出 {zip_path} ({count} 个文件, {size / 1024:.1f} KB)")
    print(f"  版本 {m['version']} · 模块 {len(m['provides']['modules'])} · "
          f"依赖 {list(m['dependencies'])}")


def cmd_import(a) -> None:
    zf = Path(a.file).expanduser()
    if not zf.is_file():
        raise SystemExit(f"没有 zip: {zf}")
    with zipfile.ZipFile(zf) as z:
        names = z.namelist()
        if "pack.json" not in names:
            raise SystemExit("zip 里没有 pack.json, 不是资产包")
        with tempfile.TemporaryDirectory() as td:
            tmp = Path(td)
            z.extractall(tmp)
            m = load_manifest(tmp)
            fill_manifest_defaults(m, tmp)
            if not ID_RE.match(m.get("id", "")):
                raise SystemExit(f"非法 pack id: {m.get('id')}")
            if not SEMVER.match(m["version"]):
                raise SystemExit(f"非法版本: {m['version']}")
            misses = []
            for rel, sha in m.get("files", {}).items():
                f = tmp / rel
                if not f.is_file():
                    misses.append(f"{rel} (文件缺失)")
                elif file_sha256(f) != sha:
                    misses.append(f"{rel} (校验和失败)")
            if misses:
                raise SystemExit("校验失败:\n  " + "\n  ".join(misses))
            has_mods = any(any((tmp / "modules").rglob("*" + suf))
                           for suf in S.SUPPORTED_SUFFIXES) \
                if (tmp / "modules").is_dir() else False
            if not has_mods:
                raise SystemExit("资产包没有 modules/*.schem(或 .litematic)")
            if a.dry_run:
                print(f"dry-run OK: {m['id']} {m['version']}, "
                      f"{len(m.get('files', {}))} 文件校验通过, "
                      f"依赖 {list(m.get('dependencies', {}))}")
                return
            target = packs_dir() / m["id"]
            if target.exists() and not a.force:
                raise SystemExit(f"已存在资产包 {m['id']}; 用 --force 覆盖")
            if target.exists():
                backup = repo_root() / ".cache" / "backups" / \
                    f"{m['id']}-{int(time.time())}"
                backup.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(target), str(backup))
                print(f"旧包已备份 -> {backup}")
            shutil.copytree(tmp, target)
            pack_ids = {pd.name for pd in pack_dirs()}
            missing = [d for d in m.get("dependencies", {})
                       if d not in pack_ids]
            if missing:
                print("WARN 依赖缺失:", ", ".join(missing))
            idx = module_scan()
            for pd in pack_dirs():
                refresh_manifest(pd, idx=idx, write=True)
            print(f"导入完成: {m['id']} {m['version']} -> {target}")


def cmd_import_modules(a) -> None:
    """Batch-import structure files as modules into a pack (storage: .schem)."""
    from mccore import library as LB  # noqa: PLC0415 (延迟导入避免环)

    src = Path(a.path).expanduser()
    if not src.exists():
        raise SystemExit(f"没有路径: {src}")
    if src.is_file():
        files = [src] if S.is_structure(src) else []
    else:
        files = sorted(p for suf in S.SUPPORTED_SUFFIXES
                       for p in src.glob("**/*" + suf) if p.is_file())
    if not files:
        raise SystemExit(f"在 {src} 没找到 .schem/.litematic")
    tags = [t.strip() for t in a.tags.split(",") if t.strip()]
    rep = LB.import_files(files, a.pack, category=a.category, flat=a.flat,
                          tags=tags, description=a.description, move=a.move,
                          overwrite=a.overwrite, embed=a.embed,
                          dry_run=a.dry_run)
    for it in rep["imported"]:
        print(f"[{'dry' if a.dry_run else 'ok'}] {Path(it['file']).name} -> "
              f"{it['category']}/{it['id']} "
              f"({'x'.join(map(str, it['size']))})")
    for it in rep["skipped"]:
        print(f"[skip] {Path(it['file']).name}: {it['reason']}")
    for it in rep["failed"]:
        print(f"[FAIL] {Path(it['file']).name}: {it['error']}")
    print()
    print(f"导入 {len(rep['imported'])} / 跳过 {len(rep['skipped'])} / "
          f"失败 {len(rep['failed'])}（目标包 {a.pack}）")


def cmd_previews(a) -> None:
    from mccore import library as LB  # noqa: PLC0415

    pd = packs_dir() / a.pack
    if not (pd / "pack.json").is_file():
        raise SystemExit(f"没有资产包 {a.pack}")
    rep = LB.render_previews(a.pack, force=a.force, online=a.online)
    for mid in rep["rendered"]:
        print(f"[ok] {mid}")
    for mid in rep["skipped"]:
        print(f"[skip] {mid} 已有预览")
    for it in rep["failed"]:
        print(f"[FAIL] {it['id']}: {it['error']}")
    print(f"完成: 新渲染 {len(rep['rendered'])} 个模块")
    cmd_scan(None)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("list", help="列出资产包").set_defaults(fn=cmd_list)
    sub.add_parser("scan", help="重建索引 + 刷新 manifest/catalog").set_defaults(fn=cmd_scan)
    sub.add_parser("validate", help="校验 manifest/files/依赖/预览").set_defaults(fn=cmd_validate)
    p = sub.add_parser("catalog", help="生成 Tier-0 紧凑目录(全库或指定包)")
    p.add_argument("pack", nargs="?", default=None)
    p.set_defaults(fn=cmd_catalog)
    p = sub.add_parser("search", help="Tier-1 结构化检索(可限定包)")
    p.add_argument("pack", nargs="?", default=None)
    p.add_argument("--query")
    p.add_argument("--category")
    p.add_argument("--tag")
    p.add_argument("--material")
    p.add_argument("--min-blocks", type=int)
    p.add_argument("--max-blocks", type=int)
    p.add_argument("--has-port", action="store_true", default=None)
    p.add_argument("--no-port", action="store_true",
                   help="只看无接口模块(摆件/装饰)")
    p.add_argument("--json", action="store_true")
    p.set_defaults(fn=cmd_search)
    p = sub.add_parser("export", help="导出可分发的 zip 到 dist/")
    p.add_argument("pack")
    p.add_argument("--out", default=None)
    p.set_defaults(fn=cmd_export)
    p = sub.add_parser("import", help="导入资产包 zip")
    p.add_argument("file")
    p.add_argument("--force", action="store_true", help="覆盖已存在的同名包(旧包备份到 .cache/backups)")
    p.add_argument("--dry-run", action="store_true", help="只校验, 不落盘")
    p.set_defaults(fn=cmd_import)
    p = sub.add_parser("import-modules",
                       help="批量导入 .schem/.schem 为模块（自动尺寸/spec/去重）")
    p.add_argument("path", help=".schem/.schem 文件或目录")
    p.add_argument("--pack", default="modern-arch", help="目标资产包")
    p.add_argument("--category", default=None, help="统一分类（不给则用子目录名）")
    p.add_argument("--flat", action="store_true", help="忽略子目录，统一放 imported/")
    p.add_argument("--tags", default="", help="逗号分隔标签")
    p.add_argument("--description", default="", help="统一描述")
    p.add_argument("--move", action="store_true", help="移动而非复制")
    p.add_argument("--overwrite", action="store_true")
    p.add_argument("--embed", action="store_true",
                   help="把 spec 也写进 litematic Metadata")
    p.add_argument("--dry-run", action="store_true", help="只列清单")
    p.set_defaults(fn=cmd_import_modules)
    p = sub.add_parser("previews", help="为包内模块渲染预览图(iso + 缩略图)")
    p.add_argument("pack")
    p.add_argument("--force", action="store_true")
    p.add_argument("--online", action="store_true", help="允许联网拉 mcassets(默认离线)")
    p.set_defaults(fn=cmd_previews)
    a = ap.parse_args()
    a.fn(a)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())