"""导出「上方压着这个方块时，墙要不要立中心柱」的方块名表。

原版 ``WallBlock#shouldRaisePost(state, above, aboveShape)`` 判的是**上方方块的 shape**
（Minecraft Wiki：柱子会在上方方块盖住「方块顶面中心四格」时立起 —— 除非墙在**对边
两侧都抬起了顶面**，也就是 north/south 或 east/west 都是 ``tall``）。

我们的重算器（``mckit.update``）只看得到**方块名**（邻居查询返回名字），所以这里用
mcrender 的模型几何离线算一张名表：

* 判据 = 该方块**任意一个变体**的几何，其 x/z 覆盖面包含中心 2×2 格
  （``x∈[7/16, 9/16]``、``z∈[7/16, 9/16]``）—— 墙柱占 x/z 4..12，柱顶接触的就是中心那 4 格；
* 特判方块（箱子/旗帜/告示牌…）资源包里没有元素，几何在 ``entity_models.json`` 里 →
  靠 ``ModelResolver`` 统一解析（它会走特判表），拿四边形位置算覆盖面；
* 流体没有 shape → 不算。

用法：``python tools/export_center_cover.py [--version 26.2]``
输出：``packages/mckit/data/center_cover.json``
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages"))

import numpy as np  # noqa: E402

from mcrender.assets import auto_assets  # noqa: E402
from mcrender.model import ModelResolver  # noqa: E402

OUT = ROOT / "packages" / "mckit" / "data" / "center_cover.json"
LO, HI = 7 / 16, 9 / 16          # 中心 2×2（1/16 单位）


def covers(bb) -> bool:
    """这个方块的几何有没有盖住中心 2×2（1/16 格）？

    用**整个几何的 x/z 包围盒**判：单个面只是一张平面（箱子的侧面在某一轴上不张开），
    逐面判会把链子、旗帜这种正确覆盖中心的方块漏掉。包围盒对箱状元素就等于
    「元素 from/to 的 x/z 范围」，与原版按 shape 判「中心四格」的语义一致。
    """
    if not bb or not bb.quads:
        return False
    xs = np.concatenate([q.pos[:, 0] for q in bb.quads]) * 16
    zs = np.concatenate([q.pos[:, 2] for q in bb.quads]) * 16
    return (xs.min() <= LO * 16 + 1e-6 and xs.max() >= HI * 16 - 1e-6
            and zs.min() <= LO * 16 + 1e-6 and zs.max() >= HI * 16 - 1e-6)


def props_of_variant(key: str) -> dict:
    out = {}
    for part in (key or "").split(","):
        if "=" in part:
            k, v = part.split("=", 1)
            out[k.strip()] = v.strip()
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default="26.2")
    a = ap.parse_args()
    assets = auto_assets(version=a.version, verbose=False)
    r = ModelResolver(assets)
    names = sorted(p.stem for p in (ROOT / ".cache" / "mcassets" / a.version
                                    / "blockstates").glob("*.json"))
    if not names:
        print("找不到 blockstates（先跑一次 mcrender 让 mcassets 缓存下来）")
        return 2
    hit, miss = [], 0
    for name in names:
        bs = assets.blockstate(name)
        if not bs:
            continue
        try:
            if "variants" in bs:
                tried = []
                for key in list(bs["variants"])[:64]:        # 同一方块的所有变体都试
                    tried.append(r.resolve_block(name, props_of_variant(key)))
            else:
                tried = [r.resolve_block(name, {})]          # multipart：默认属性够了
        except Exception:  # noqa: BLE001
            miss += 1
            continue
        if any(covers(bb) for bb in tried):
            hit.append(name)
    payload = {
        "_note": "generated by tools/export_center_cover.py —— 方块的几何盖住中心 2×2 格"
                 "（上方压着它时墙会立中心柱；见 mckit.connect.wall_state）",
        "version": a.version,
        "blocks": hit,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")
    print(f"{len(names)} 个方块 → {len(hit)} 个会压住中心（{miss} 个解析失败） → {OUT}")
    for probe in ("stone", "flower_pot", "oak_slab", "oak_stairs", "oak_fence", "torch", "chain", "oak_door",
                  "glass_pane", "chest", "iron_bars", "water", "oak_leaves", "oak_pressure_plate"):
        print(f"   {probe:22s} {'压中心' if probe in hit else '不压中心'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
